#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: bc4b71b1-a5f2-4558-aaaf-d685162e9782
# Source File: ..\OneDrive\Dokumenty\SAPIEN\PowerShell Studio\Projects\xmr\MainForm.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
VQQAAB+LCAAAAAAABABllMmuqloQhucmvsPOmZocGlEw8ewEpBGBBdKJzOgXsuik5+mvZ9/JTW6N
KvWnKlX58tfZTKJ6TN4LH/TB1yfp8rr682v/m/j1vd18fZ31d57lVYDEHCUgKJNvLcgrsX6Xv5su
PWP/k3+a/urfuj7TRFZBlXNY9qLzF/bf4Fg+foj9WK7sM/V3OEby84uT5R73lYJTLKs3LIH1Hgby
o0rei5SWP99DOVaUVGw3L/+p3mBb5w17XwCGqKtB0RrDkxgD2EMbeDTDaheYsoAYKJGb+rwUoyRq
rEJlbrt99JwVL56lSPrstd3Ii9nAmw7J5rpYk/mAJZQo/sJJlpMInZAzhOCkchyKxxPUxjuYTtrF
9lM6z1o00BQr5KeydKOuyhd2u6HERLh3asexXYWki3PJXI2rTI5hn9bQ44cXryhVxPERp4qahjhN
BDGnystRP4CWmNKIzUTmcEDtePe3m4S5BlOW2ZM5ieDacuidQFUqUU05n5vYKil13wVuxhpuC6+A
FJk5t/Om91KoMBSTMeG1Ocke2vcV2G46Lh2eL7paKTBoYb1/xyG3GhoM0CQrGrNIYWVbpExNZDEv
Fn2jgKhd+VGLdB5xbFvWL4XKOxo6J3X5UGh4vqasopVnMmOM6JTOo3WHKZf+pd58qBu312wGOjhO
IfY0V570CsnJnVRd19sdDK1TGK3LXof1sN3EUkHTHSTIXr/hMObGw0HjK25pj4+RcJ8q2j8ggvKd
Elz8cWx8uyFFw0sDZcFPShJbukVTIv5YIVP2240EyPpt5kmEorbJgoAkFJUoDwj3PsOU27zghgJm
kiA0wd7Roez2w/sS3syKXIh7eDs8e+ZBOi3tgzTebh6Y3ImnxFpNg+671wCcmdy/jkvqOo5wW3Px
/tDR0WafsU4IhWjQ8BXAus4atxMgqWsTei+F13Vmt/9MY/ETStzIQOsdIzTNHiaPePFAiWKFSo0p
XyNzV3ZYhyeW4g8gg35cnNqRTNT2WHS1PYTogFKwK/CO3G6uzJRUqx7Rdrwvb++37BylRF6tVQA6
Bpm40h4RszLMTmWfxG6wNayJeINYBUPxg1MlCrSKjXveDa/+hwK42v2QO4RXFbo3BkabFt4qAsu5
TO7Htn/O2I+tfwzOdl1ShihPui/sUzlj/30j3/8AWkox/FUEAAA=#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2020 v5.7.172
     Generated on:       02.02.2022 05:50
     Generated by:       piotr
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2020
#>


#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-MainForm_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$labelDATE = New-Object 'System.Windows.Forms.Label'
	$labelMONEROSTATS = New-Object 'System.Windows.Forms.Label'
	$labelRESPONSE = New-Object 'System.Windows.Forms.Label'
	$label5 = New-Object 'System.Windows.Forms.Label'
	$label4 = New-Object 'System.Windows.Forms.Label'
	$label3 = New-Object 'System.Windows.Forms.Label'
	$label2 = New-Object 'System.Windows.Forms.Label'
	$buttonDOWNLOADSTATS = New-Object 'System.Windows.Forms.Button'
	$label1 = New-Object 'System.Windows.Forms.Label'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$form1_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	$buttonDOWNLOADSTATS_Click={
		#TODO: Place custom script here
		$STATS = Invoke-RestMethod -Method Get -Uri 'https://minexmr.com/api/main/user/stats?address=89eo7KG9FWnjMqsDELaS2BKPPQfGi4u7sRLxh1NqeTHUbASucvmTHKrSTbzt2ZyZbj7tEVXrNaXLJe6ZnBPRjFT6B4Ka3Hj&27396256'
		$BALANCE = Select-Object -InputObject $STATS.balance
		$BALANCED= $BALANCE / 1000000000000
		$label1.Text = $BALANCED
		$CURR = Invoke-RestMethod -Method Get 'https://api.coinpaprika.com/v1/price-converter?base_currency_id=xmr-monero&quote_currency_id=pln-polish-zloty&amount=1'
		$label2.Text = $CURR.base_currency_name
		$label3.Text = $CURR.quote_price_last_updated
		$label4.Text = $CURR.price
		$label5.Text = $CURR.quote_currency_name
		$labelRESPONSE.Text = 'RESPONSE OK'
		
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonDOWNLOADSTATS.remove_Click($buttonDOWNLOADSTATS_Click)
			$form1.remove_Load($form1_Load)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($labelDATE)
	$form1.Controls.Add($labelMONEROSTATS)
	$form1.Controls.Add($labelRESPONSE)
	$form1.Controls.Add($label5)
	$form1.Controls.Add($label4)
	$form1.Controls.Add($label3)
	$form1.Controls.Add($label2)
	$form1.Controls.Add($buttonDOWNLOADSTATS)
	$form1.Controls.Add($label1)
	$form1.AutoScaleDimensions = '6, 13'
	$form1.AutoScaleMode = 'Font'
	$form1.BackColor = 'ActiveCaption'
	$form1.ClientSize = '447, 163'
	$form1.Name = 'form1'
	$form1.Text = 'Form'
	$form1.add_Load($form1_Load)
	#
	# labelDATE
	#
	$labelDATE.AutoSize = $True
	$labelDATE.Location = '340, 36'
	$labelDATE.Name = 'labelDATE'
	$labelDATE.Size = '34, 17'
	$labelDATE.TabIndex = 8
	$labelDATE.Text = 'DATE'
	$labelDATE.UseCompatibleTextRendering = $True
	#
	# labelMONEROSTATS
	#
	$labelMONEROSTATS.AutoSize = $True
	$labelMONEROSTATS.Location = '339, 9'
	$labelMONEROSTATS.Name = 'labelMONEROSTATS'
	$labelMONEROSTATS.Size = '95, 17'
	$labelMONEROSTATS.TabIndex = 7
	$labelMONEROSTATS.Text = 'MONERO STATS'
	$labelMONEROSTATS.UseCompatibleTextRendering = $True
	#
	# labelRESPONSE
	#
	$labelRESPONSE.AutoSize = $True
	$labelRESPONSE.Location = '205, 133'
	$labelRESPONSE.Name = 'labelRESPONSE'
	$labelRESPONSE.Size = '67, 17'
	$labelRESPONSE.TabIndex = 6
	$labelRESPONSE.Text = 'RESPONSE'
	$labelRESPONSE.UseCompatibleTextRendering = $True
	#
	# label5
	#
	$label5.AutoSize = $True
	$label5.Location = '339, 62'
	$label5.Name = 'label5'
	$label5.Size = '0, 16'
	$label5.TabIndex = 5
	$label5.UseCompatibleTextRendering = $True
	#
	# label4
	#
	$label4.AutoSize = $True
	$label4.Location = '217, 62'
	$label4.Name = 'label4'
	$label4.Size = '0, 16'
	$label4.TabIndex = 4
	$label4.UseCompatibleTextRendering = $True
	#
	# label3
	#
	$label3.AutoSize = $True
	$label3.Location = '217, 36'
	$label3.Name = 'label3'
	$label3.Size = '0, 16'
	$label3.TabIndex = 3
	$label3.UseCompatibleTextRendering = $True
	#
	# label2
	#
	$label2.AutoSize = $True
	$label2.Font = 'Microsoft Sans Serif, 21.75pt, style=Bold'
	$label2.Location = '12, 23'
	$label2.Name = 'label2'
	$label2.Size = '0, 36'
	$label2.TabIndex = 2
	$label2.UseCompatibleTextRendering = $True
	#
	# buttonDOWNLOADSTATS
	#
	$buttonDOWNLOADSTATS.Location = '301, 128'
	$buttonDOWNLOADSTATS.Name = 'buttonDOWNLOADSTATS'
	$buttonDOWNLOADSTATS.Size = '134, 23'
	$buttonDOWNLOADSTATS.TabIndex = 1
	$buttonDOWNLOADSTATS.Text = 'DOWNLOAD STATS'
	$buttonDOWNLOADSTATS.UseCompatibleTextRendering = $True
	$buttonDOWNLOADSTATS.UseVisualStyleBackColor = $True
	$buttonDOWNLOADSTATS.add_Click($buttonDOWNLOADSTATS_Click)
	#
	# label1
	#
	$label1.AutoSize = $True
	$label1.Location = '217, 9'
	$label1.Name = 'label1'
	$label1.Size = '0, 16'
	$label1.TabIndex = 0
	$label1.UseCompatibleTextRendering = $True
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call the form
Show-MainForm_psf | Out-Null
